/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://3ycfdrr3n5gh7glaaqs2ugfc5e.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-o5wobcujrvg5rnsx4vegc5ppaq',
  aws_cognito_identity_pool_id:
    'us-east-1:3ab42053-ba0d-4caf-824f-9d63aeb1387b',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_3NT6yM1BZ',
  aws_user_pools_web_client_id: '282i7kri59mecifdjb308fvhtu',
  oauth: {},
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_UPPERCASE',
      'REQUIRES_NUMBERS',
      'REQUIRES_SYMBOLS',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_user_files_s3_bucket: 'adgadmin170407-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
